[project]
name = "keras-classify"
version = "0.1.0"
description = "keras introduction"
 authors = [
    {name = "Intri Desktop", email = "intriqet@outlook.com"},
]
dependencies = [
    'pandas',
    'numpy==1.7',
    'matplotlib',
    'keras',
    'scikit-learn',
    'ruff',
    'pytest',
    'loguru',
    "requests>=2.32.3",
    "tensorflow[and-cuda]<2.11",
    "ipython"
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true
